version: '3.4'

services:
  # rabbit:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbit1"
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #     RABBITMQ_DEFAULT_USER: "rabbitmq"
  #     RABBITMQ_DEFAULT_PASS: "rabbitmq"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   expose:
  #     - "27017"
  #   labels:
  #     NAME: "rabbitmq1"
    # volumes:
    #   - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      
  mongo:
    image: 'mongo'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: chat_app
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data:/data/db
    networks:
      - backend

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      MONGODB_URL: '0.0.0.0:27017'
      MONGODB_USER: root
      MONGODB_PASS: admin
      MONGODB_AUTH_SOURCE: admin
      MONGODB_DB: chat_app
      MONGODB_AUTH_MECANISM: SCRAM-SHA-256
      RABBITMQ_USER: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq
      RABBITMQ_HOST: '0.0.0.0'
    networks:
      - backend

  # chatbot:
  #   build:
  #     context: ./bot_server
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 8000:5000
  #   environment:
  #     RABBITMQ_USER: rabbitmq
  #     RABBITMQ_PASSWORD: rabbitmq
  #     RABBITMQ_HOST: '0.0.0.0'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge